### ISSUE TITLE
Un compte, plusieurs linkys, Bad access token

### ISSUE THREAD

**Issue by qdel** [russandol-sarl/Device-Flow-Proxy-Server#16]
Bonjour,
 
Je dispose de 2 linky sur un compte enedis. La demande de consentement se fait bien et je recoit en fin de demande la liste usage_points_id avec mes 2 PDL.

Cependant, quand je souhaite obtenir les données, en placant le champ usage_point_id a l'un de mes compteurs, je recoit systématiquement une erreur:
```json
{
    "error": "Unauthorized",
    "error_description": "Bad access token"
}
```
https://github.com/russandol-sarl/Device-Flow-Proxy-Server/blob/master/src/Controller/Controller.php#L596

Cela me force, de mon coté a faire une demande de refresh du token. Avec le champ usage_points_id placé a la valeur originelle de la liste fournit par la demande de consentement. Cette demande fonctionne sans soucis.

**Comment by oredin** [comment]
A suivre sur le dépôt principal.
