### ISSUE TITLE
404 On enedis website

### ISSUE THREAD

**Issue by qdel** [russandol-sarl/Device-Flow-Proxy-Server#2]
Hi,

When using https://enedis.domoticz.russandol.pro/device?code=XXXX-XXXX and clicking on enedis userspace login, i meet a 404 (on enedis website).

Thanks

**Comment by oredin** [comment]
Hi,

Enedis has some problems on their APIs. I had a mail notification about the unavaibility of the Authorize API today.

We have to wait fot them to fix their problem.

I'll keep you updated when I have some news from them.

**Comment by oredin** [comment]
Hi,

According to Enedis, the problem should be fixed on monday afternoon.

**Comment by oredin** [comment]
Quick update : Enedis is still working on the bug. The new ETA is now sometime during this week !

**Comment by qdel** [comment]
-_-'

Ok, waiting...

**Comment by oredin** [comment]
Just got an email from Enedis telling me that the API is back online.

It could take some times for the plugin to get back on track since there're many users of this plugin and Enedis is limiting the rate of API calls.

**Comment by qdel** [comment]
Just tried it and it worked flawlessly :)

Thanks for your reporting !
