### ISSUE TITLE
Unable to renew credential to Enedis services

### ISSUE THREAD

**Issue by vzwingma** [russandol-sarl/Device-Flow-Proxy-Server#3]
I would like to renew credentials to Enedis service for my "Linky device" on Domoticz; with this endpoint : https://enedis.domoticz.russandol.pro/device?code=PAQK-GLSA

When I allow Enedis to share my data; I've got this error 

![image](https://user-images.githubusercontent.com/10505762/121521067-e9b32600-c9f3-11eb-87dd-96b8eaff19f1.png)

for this URL : 

https://enedis.domoticz.russandol.pro/auth/redirect?code=B6sUr6m2WFEqQeOzFku7MtSR8K0USO&state=a1732bc995c60a8ea65389399bdce713&usage_point_id=21312735030453

And Domoticz doesn't retrieve any data.
However, I received an email from Enedis which confirm the data sharing

![image](https://user-images.githubusercontent.com/10505762/121523280-54fdf780-c9f6-11eb-8dd3-eeec9e8e33a2.png)

**Comment by oredin** [comment]
Hi,

See https://github.com/guillaumezin/DomoticzLinky/issues/138.
