### ISSUE TITLE
invalid submit request 

### ISSUE THREAD

**Issue by pboutarin** [russandol-sarl/Device-Flow-Proxy-Server#5]
Hello,

quand on essaye de soumettre la demande d'authentification 
_https://enedis.domoticz.russandol.pro/auth/verify_code?code=ABCD-EFGH&state=&btnSubmit=_

j'obtiens une erreur invalid request
![image](https://github.com/russandol-sarl/Device-Flow-Proxy-Server/assets/98038592/38399047-cf17-493d-b09a-72ccae033baa)

Merci

**Comment by oredin** [comment]
Les problèmes doivent être remontés au développeur via https://github.com/guillaumezin/Device-Flow-Proxy-Server.
